### ISSUE TITLE
Only POST method

### ISSUE THREAD

**Issue by ricardorlg** [crazylab/fake-server#5]
Is possible to mock a response to only POST method, I mean I want to mock a post METHOD, no matters the body, and in the responses return the body params.

**Comment by crazylab** [comment]
Hi @ricardorlg,
Sorry for the delay in response. You can certainly achieve that by setting your payload as `null`. In that case, it will match all your request ignoring the payload section. 

```json
{
  "route": "/test",
  "responseCode": 200,
  "responseBody": "yay it matches",
  "payload" : null
}
```
This will match all the post request to `/test`.
But the only problem is that it will match other type of request also like `GET` etc at this moment because there is no wildcard support available in the framework yet. If you can live with that, you can go ahed and use it.
